(async(message,nextUnit)=>{
 const allCards=[...load("cards2"),...load("cards3")],allKnowledge=[...load("knowledge2"),...load("knowledge3")],allUnits=[...load("units2"),...load("units3")],allFigures=[...load("figures2"),...load("figures3")],allGaps=[...load("gaps2"),...load("gaps3")],allHandling={...load("handling2"),...load("handling3")};
 const prog={source_snapshot:"1cca4eb09d83ec631136f60e9dc7dd0e05df843c",textbook_material_commit:"b036244ba7c8f82d6c35602a5e570d6729b0bee4",assigned_chapters:[2,3],assigned_extra_scope:load("extra_sources")||[],actually_read_scope:Object.groupBy(allUnits.filter(u=>u.reading_status==="actually_read"),u=>u.block_id),cards:allCards.length,knowledge:allKnowledge.length,covered_knowledge:allKnowledge.filter(x=>x.status==="covered").length,original_images_actually_viewed:allFigures.length,read_units:allUnits.filter(x=>x.reading_status==="actually_read").length,unread_units:allUnits.filter(x=>x.reading_status!=="actually_read").length,unresolved_items:allGaps.filter(g=>g.status==="unresolved").length,last_card_id:allCards.at(-1)?.id,next_unit:nextUnit,full_assigned_scope_complete:false};
 prog.actually_read_scope=Object.fromEntries(Object.entries(prog.actually_read_scope).map(([b,us])=>[b,{first:us[0].id,last:us.at(-1).id,count:us.length}]));
 store("progress",prog);
 const data={"cards.json":{cards:allCards},"knowledge.json":allKnowledge,"read_units.json":allUnits,"handling.json":allHandling,"figures.json":allFigures,"gaps.json":allGaps,"progress.json":prog,"source_manifest.json":{snapshot:prog.source_snapshot,textbook_material_commit:prog.textbook_material_commit,extra_sources:load("extra_sources")||[],original_pdf_reviews:load("pdf_reviews")||[],files:[2,3].flatMap(ch=>[{file:(ch===2?"02_细胞生物学研究方法":"03_细胞质膜")+"/整合教材.md",git_blob_sha:load("source"+ch).sha},load("suppsource"+ch)]),skill:"skill://user/6ac74bcc13e08191956116fab528f6d7/make-biology-anki/SKILL.md"},"author_helpers.js":load("author_helper"),"english_author_helper.js":load("english_author_helper"),"checkpoint_helper.js":load("checkpoint_helper")};
 const blobs=await Promise.allSettled(Object.entries(data).map(async([f,v])=>{const r=await tools.mcp__codex_apps__github_create_blob({repository_full_name:"kazewwk/test",encoding:"utf-8",content:typeof v==="string"?v:JSON.stringify(v,null,2)});return {f,r};}));
 const entries=[];for(const b of blobs){if(b.status!=="fulfilled"||b.value.r.isError)throw Error(JSON.stringify(b));const {f,r}=b.value;const sha=r.structuredContent?.sha;entries.push({path:"anki/SHU_Cell_Biology_Full_20261010/input/ch02_ch03/"+f,mode:"100644",type:"blob",sha});}
 for(const f of allFigures)entries.push({path:"anki/SHU_Cell_Biology_Full_20261010/input/ch02_ch03/media/"+f.filename,mode:"100644",type:"blob",sha:f.git_blob_sha});
 const tr=await tools.mcp__codex_apps__github_create_tree({repository_full_name:"kazewwk/test",base_tree_sha:load("tree"),tree_elements:entries});if(tr.isError)throw Error(JSON.stringify(tr));const tree=tr.structuredContent.sha;
 const cr=await tools.mcp__codex_apps__github_create_commit({repository_full_name:"kazewwk/test",message,parent_sha:load("head"),tree_sha:tree});if(cr.isError)throw Error(JSON.stringify(cr));const head=cr.structuredContent.sha;
 const ref=await tools.mcp__codex_apps__github_update_ref({repository_full_name:"kazewwk/test",branch_name:"anki-full-20261010-cn02-cn03",sha:head,expected_sha:load("head")});if(ref.isError)throw Error(JSON.stringify(ref));
 store("head",head);store("tree",tree);store("lastEntries",entries);return {head,tree,files:entries.filter(e=>!e.path.includes("/media/")),progress:prog};
})